### ISSUE TITLE
NPE during Expanding pod under Nodes -> OpenshiftMaster element and calling a ContextMenu (right mouse click)

### ISSUE THREAD

**Issue by odockal** [redhat-developer/intellij-kubernetes#109]
Steps:
1. ASSERT: make sure you're on the "openshift" namespace
1. EXEC: expand Nodes > <node>
1. ASSERT: all existing pods are listed
1. EXEC: expand a node
1. ASSERT: Running state and IP children are expanded
1. EXEC: right click on running child

![image](https://user-images.githubusercontent.com/25126/99119787-18058a00-25fa-11eb-9853-bfa63783dd5d.png)

Result:
an error notification pops up reporting an error in the IDE. Looking into the log you'll find lots of these entries:
```
update failed for AnAction(org.jboss.tools.intellij.kubernetes.actions.UseNamespaceAction) with ID=org.jboss.tools.intellij.kubernetes.actions.UseNamespaceAction

java.lang.NullPointerException
	at com.redhat.devtools.intellij.common.actions.TreeAction.lambda$isVisible$3(TreeAction.java:83)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.noneMatch(ReferencePipeline.java:459)
	at com.redhat.devtools.intellij.common.actions.TreeAction.isVisible(TreeAction.java:83)
	at com.redhat.devtools.intellij.common.actions.TreeAction.update(TreeAction.java:68)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:171)
	at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:202)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:151)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:295)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:109)
	at com.intellij.ui.PopupHandler$2.invokePopup(PopupHandler.java:88)
	at com.intellij.ui.PopupHandler.mousePressed(PopupHandler.java:40)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.Component.processMouseEvent(Component.java:6545)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:409)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4523)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:664)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by odockal** [comment]
It is not precise reproduction step, but one can play around to get this NPE. try expanding nodes and trying to invoke context menu item. It happens when there are no context item available...

**Comment by odockal** [comment]
Seems to be the element with IP address...

**Comment by jkopriva** [comment]
I get an NPE when setting new default project.

**Comment by adietish** [comment]
ps. it wasn't obvious to me how to replicate this. Could you please provide more details about the steps to take in your upcoming issues? I'd appreciate this a lot.

**Comment by adietish** [comment]
filed to https://github.com/redhat-developer/intellij-common/issues/19

**Comment by adietish** [comment]
@odockal, @jkopriva this was fixed in https://github.com/redhat-developer/intellij-common/pull/20. You can either wait for intellij-common to be published or build it locally. It should fix the issue at hand. Please verify, thanks.
