### ISSUE TITLE
java.nio.file.NoSuchFileException: ~/.kube in console if ".kube" folder is missing

### ISSUE THREAD

**Issue by olkornii** [redhat-developer/intellij-kubernetes#119]
Steps to reproduce git clone intellij-kubernetes -> run ./gradlew runIde -> Error (but Intellij starts):

Gtk-Message: 10:38:41.842: Failed to load module "canberra-gtk-module"
java.nio.file.NoSuchFileException: /home/olkornii/.kube
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.asIOException(UnixException.java:111)
        at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:246)
        at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260)
        at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:364)
        at java.lang.Thread.run(Thread.java:745)

**Comment by adietish** [comment]
@olkornii looks like you're missing a kube config. You're reporting that intellij is running, is the kubernetes toolwindow visible? does it show anything?

**Comment by adietish** [comment]
the tool window is visible but stays empty which is expected because there's nothing to show.
The stacktrace on MacOS is 
```
java.nio.file.NoSuchFileException: /Users/andredietisheim/.kube
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at sun.nio.fs.PollingWatchService.doPrivilegedRegister(PollingWatchService.java:147)
	at sun.nio.fs.PollingWatchService.access$000(PollingWatchService.java:45)
	at sun.nio.fs.PollingWatchService$2.run(PollingWatchService.java:128)
	at sun.nio.fs.PollingWatchService$2.run(PollingWatchService.java:125)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.nio.fs.PollingWatchService.register(PollingWatchService.java:124)
	at sun.nio.fs.UnixPath.register(UnixPath.java:897)
	at com.redhat.devtools.intellij.common.utils.HighSensitivityRegistrar.registerService(HighSensitivityRegistrar.java:69)
	at com.redhat.devtools.intellij.common.utils.ConfigWatcher.registerWatchService(ConfigWatcher.java:82)
	at com.redhat.devtools.intellij.common.utils.ConfigWatcher.runOnConfigChange(ConfigWatcher.java:62)
	at com.redhat.devtools.intellij.common.utils.ConfigWatcher.run(ConfigWatcher.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745) 
```

**Comment by adietish** [comment]
This is an issue in intellij-common as the stacktrace shows.

**Comment by adietish** [comment]
replaced by https://github.com/redhat-developer/intellij-common/issues/17
Closing.
