### ISSUE TITLE
IDE Error: commitDocument() left PSI inconsistent

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#236]
**Steps:**
1. ASSERT: have pod running
2. EXEC: open pod in editor
3. EXEC: replace editor with the following deployment: 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sise-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sise
  template:
    metadata:
      labels:
        app: sise
    spec:
      containers:
      - name: sise
        image: quay.io/openshiftlabs/simpleservice:0.5.0
        ports:
        - containerPort: 9876
        env:
        - name: SIMPLE_SERVICE_VERSION
          value: "0.9"
```
4. ASSERT: notification to push and create new resource appears 
5. EXEC: hit "Push"
6. ASSERT: new deployment is created, 2 new pods for the deployment are create

**Result**:
IDE error appears with the following:
```
java.lang.Throwable: commitDocument() left PSI inconsistent: not committed document DocumentImpl[file:///private/var/folders/2t/l3zqx5ks1gl2c9lkd0yxy80m0000gn/T/intellij-kubernetes/sise-deploy@default.yml], File[YAML file sise-deploy@default.yml, Language: yaml, SingleRootFileViewProvider{myVirtualFile=file:///private/var/folders/2t/l3zqx5ks1gl2c9lkd0yxy80m0000gn/T/intellij-kubernetes/sise-deploy@default.yml, content=com.intellij.psi.AbstractFileViewProvider$PsiFileContent@f6bf9bb}]; node.length=2574; doc.text!=file.text; file name:sise-deploy@default.yml; type:org.jetbrains.yaml.YAMLFileType@1e6e619f; lang:Language: yaml
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at com.intellij.psi.impl.DocumentCommitThread.assertAfterCommit(DocumentCommitThread.java:723)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$doCommit$7(DocumentCommitThread.java:712)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitToExistingPsi(PsiDocumentManagerBase.java:381)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$finishCommitInWriteAction$1(PsiDocumentManagerBase.java:352)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:192)
	at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommitInWriteAction(PsiDocumentManagerBase.java:347)
	at com.intellij.psi.impl.PsiDocumentManagerImpl.finishCommitInWriteAction(PsiDocumentManagerImpl.java:151)
	at com.intellij.psi.impl.PsiDocumentManagerBase$1.run(PsiDocumentManagerBase.java:308)
	at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommit(PsiDocumentManagerBase.java:312)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$createFinishCommitInEDTRunnable$5(DocumentCommitThread.java:506)
	at com.intellij.psi.impl.DocumentCommitThread.commitSynchronously(DocumentCommitThread.java:370)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$doCommit$2(PsiDocumentManagerBase.java:439)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1057)
	at com.intellij.psi.impl.PsiDocumentManagerBase.doCommit(PsiDocumentManagerBase.java:447)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitDocument(PsiDocumentManagerBase.java:288)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$replaceDocument$2.invoke(ResourceEditor.kt:312)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$replaceDocument$2.invoke(ResourceEditor.kt:54)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$sam$com_intellij_openapi_util_ThrowableComputable$0.compute(ResourceEditor.kt)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:1023)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1073)
	at com.intellij.openapi.application.WriteAction.compute(WriteAction.java:118)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$executeWriteAction$1.run(ResourceEditor.kt:450)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:156)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by adietish** [comment]
This is a very tricky error. What I found out so far is that when you push the document to the cluster, several updates to the document happen:
1. When the client is pushing the resource it returns an updated resource. This first update is set to the document and committed flawlessly.
1. The cluster then updates the resource and sends an update via the watch. This second update is set to the document, too. But the commit for it is not executed. Causing the exception.
The reason for the 2nd update to not get executed is the following:
The document is considered as committed and thus the commit won't happen.
https://github.com/JetBrains/intellij-community/blob/master/platform/core-impl/src/com/intellij/psi/impl/PsiDocumentManagerBase.java#L327
```
  @Override
  public void commitDocument(@NotNull final Document doc) {
    ...
    if (!isCommitted(document)) {
      doCommit(document);
    }
  }
  ```
  `isCommitted` returns `true` because the synchronizer is currently synchronizing the document: 
  https://github.com/JetBrains/intellij-community/blob/master/platform/core-impl/src/com/intellij/psi/impl/PsiDocumentManagerBase.java#L849
```
 public boolean isCommitted(@NotNull Document document) {
    ...
    if (getSynchronizer().isInSynchronization(document)) return true;
    ...
  }
  ```

**Comment by adietish** [comment]
turns out that this was caused by a cycle:

replacing the document is invoking the editor transaction listener which then triggers an update (again). The solution is to prevent this cycle with a flag that marks that a document replacement had happened. An eventual update would then be prevented and reset the flag again.
