### ISSUE TITLE
Error when updating tekton resource

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-kubernetes#325]
I tried to open a pipeline, edit the name of a param and push it on cluster. I face a fatal error.

![error-k8s](https://user-images.githubusercontent.com/49404737/146030040-73098f19-7c34-4bdb-a3d7-52e9e02d4bb1.gif)

My pipeline
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: "2021-12-14T15:31:04Z"
  generation: 5
  name: app-sum-test
  namespace: default
  resourceVersion: "34943221"
  uid: 7f7f5534-493c-4c04-b5f7-aa1837c0840e
spec:
  params:
  - name: first
    type: string
  - name: second
    type: string
  tasks:
  - name: sum
    params:
    - name: a
      value: $(params.first)
    - name: b
      value: $(params.second)
    taskRef:
      kind: Task
      name: sum-params
```

the error
```
java.lang.Throwable: File of this document has been deleted: file:///tmp/default-newpipeline.yaml
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.openapi.editor.impl.DocumentImpl.beforeChangedUpdate(DocumentImpl.java:849)
	at com.intellij.openapi.editor.impl.DocumentImpl.updateText(DocumentImpl.java:798)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:668)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:615)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$replaceDocument$1.invoke(ResourceEditor.kt:283)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$replaceDocument$1.invoke(ResourceEditor.kt:50)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$sam$java_lang_Runnable$0.run(ResourceEditor.kt)
	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$5(WriteCommandAction.java:356)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl$1.run(WriteCommandAction.java:110)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:251)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:885)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:250)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:308)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:188)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:310)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:249)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:230)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:112)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:356)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:348)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor.runWriteCommand(ResourceEditor.kt:441)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor.replaceDocument(ResourceEditor.kt:282)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor.access$replaceDocument(ResourceEditor.kt:50)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$showPulledOrPullNotification$2.invoke(ResourceEditor.kt:223)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$showPulledOrPullNotification$2.invoke(ResourceEditor.kt:50)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$sam$java_lang_Runnable$0.run(ResourceEditor.kt)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by adietish** [comment]
@lstocchi: can't replicate this. Neither in `intellij-kubernetes` nor in `intellij-tekton` :(

**Comment by lstocchi** [comment]
Tried again and i don't face it anymore. Maybe it was fixed in one of your PR. :rocket: Thanks!!
