### ISSUE TITLE
Editor that is reopened after closing and reopening project doesn't work

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#344]
**Steps:**
1. ASSERT: have an editor for a resource/file opened
2. EXEC: close project and reopen it

**Result:**
The editor that was opened when you closed the project is reopened. It is missing the toolbar though and doesn't notify you to push to the cluster if you change the resource in it.
If you open the IJ logs (you'll notice the fatal IDE error flashing in the bottom right corner) you'll find the following:
```
java.lang.AssertionError: Already disposed: Project (name=penguins, containerState=DISPOSE_COMPLETED, componentStore=/Users/andredietisheim/git/penguins) 
	at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$0(ComponentManagerImpl.java:153)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:62)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:821)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:62)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:151)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:144)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:286)
	at com.intellij.openapi.components.ComponentManager.getService(ComponentManager.java:114)
	at com.intellij.psi.PsiDocumentManager.getInstance(PsiDocumentManager.java:35)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$8.invoke(ResourceEditor.kt:94)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$8.invoke(ResourceEditor.kt:53)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$9.invoke(ResourceEditor.kt:97)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$9.invoke(ResourceEditor.kt:53)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor.enableNonProjectFileEditing(ResourceEditor.kt:418)
	at com.redhat.devtools.intellij.kubernetes.KubernetesPluginInitializer.enableAllEditorsNonProjectEditing(KubernetesPluginInitializer.kt:42)
	at com.redhat.devtools.intellij.kubernetes.KubernetesPluginInitializer.runActivity(KubernetesPluginInitializer.kt:31)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:216)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$null$1(StartupManagerImpl.java:177)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:396)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:388)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:68)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by adietish** [comment]
the workaround is simple: close the editor and reopen your file in a new editor.

**Comment by adietish** [comment]
The problem here is that the editor does not get closed when the project is not closed. The `ResourceEditor` thus doesn't get the chance so properly clean up. Upon project open an existing instance is found an reused, causing a disposed project to be used.

**Comment by adietish** [comment]
As of 0.4.3-SNAPSHOT i cannot reproduce this any more. Closing.
