### ISSUE TITLE
IllegalArgumentException when pushing task resource in tekton

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-kubernetes#350]
Not sure if this has been fixed in current master. Needs to be verified.
I'm trying to save this task
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: foo2
spec:
  workspaces:
    - name: test
  steps:
    - name: build-sources
      image: fedora
      command:
        - /bin/bash
      args: ['-c', 'echo hello world']

```

and if i push it i receive this fatal error
```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.redhat.devtools.intellij.kubernetes.model.resource.kubernetes.custom.CustomResourceDefinitionMapping.isCustomResource, parameter resource
	at com.redhat.devtools.intellij.kubernetes.model.resource.kubernetes.custom.CustomResourceDefinitionMapping.isCustomResource(CustomResourceDefinitionMapping.kt)
	at com.redhat.devtools.intellij.kubernetes.editor.EditorResourceFactory.create(EditorResourceFactory.kt:78)
	at com.redhat.devtools.intellij.kubernetes.editor.EditorResourceFactory.create(EditorResourceFactory.kt:52)
	at com.redhat.devtools.intellij.kubernetes.editor.EditorResourceFactory.create(EditorResourceFactory.kt:37)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$1.invoke(ResourceEditor.kt:55)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$1.invoke(ResourceEditor.kt:48)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor.createResource(ResourceEditor.kt:291)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor.access$createResource(ResourceEditor.kt:48)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$update$1.invoke(ResourceEditor.kt:133)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$update$1.invoke(ResourceEditor.kt:48)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$sam$java_lang_Runnable$0.run(ResourceEditor.kt)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by lstocchi** [comment]
I wasn't able to replicate it in current master. Tested with both minikube and ocp 4.10.
