### ISSUE TITLE
IllegalStateException when binary plugin is installed in EAP 2021.3.3

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#365]
**Steps:**
1. ASSERT: have binary plugin version **0.4.1** installed in latest EAP 2021.3.3
2. EXEC: launch IDE
3. EXEC: in IDE: edit some java files, switch to other application & come back to IDE

**Result:**
![image](https://user-images.githubusercontent.com/25126/160248951-02a936fd-4222-4ec4-8375-79152f67d5ac.png)
```
java.lang.IllegalStateException: Calling invokeAndWait from read-action leads to possible deadlock.
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:455)
	at com.redhat.devtools.intellij.common.utils.UIHelper.executeInUI(UIHelper.java:34)
	at com.redhat.devtools.intellij.kubernetes.editor.KubernetesEditorTabTitleProvider.getEditorTabTitle(KubernetesEditorTabTitleProvider.kt:23)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getCustomEditorTabTitle(EditorTabPresentationUtil.java:34)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getEditorTabTitle(EditorTabPresentationUtil.java:19)
	at com.intellij.openapi.vfs.newvfs.VfsPresentationUtil.lambda$getPresentableNameForUI$0(VfsPresentationUtil.java:29)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:141)
	at com.intellij.openapi.vfs.newvfs.VfsPresentationUtil.getPresentableNameForUI(VfsPresentationUtil.java:29)
	at com.intellij.ide.actions.SearchEverywherePsiRenderer.getElementText(SearchEverywherePsiRenderer.java:66)
	at com.intellij.ide.util.PsiElementListCellRenderer$1.getPresentableText(PsiElementListCellRenderer.java:410)
	at com.intellij.ide.util.PsiElementListCellRenderer.targetPresentation(PsiElementListCellRenderer.java:443)
	at com.intellij.ide.util.PsiElementListCellRenderer.computePresentation(PsiElementListCellRenderer.java:392)
	at com.intellij.ide.actions.searcheverywhere.PSIPresentationBgRendererWrapper.lambda$createCalculator$1(PSIPresentationBgRendererWrapper.java:66)
	at com.intellij.ide.actions.searcheverywhere.PSIPresentationBgRendererWrapper.element2presentation(PSIPresentationBgRendererWrapper.java:79)
	at com.intellij.ide.actions.searcheverywhere.PSIPresentationBgRendererWrapper.lambda$fetchWeightedElements$0(PSIPresentationBgRendererWrapper.java:59)
	at com.intellij.util.containers.ContainerUtil.process(ContainerUtil.java:769)
	at com.intellij.ide.actions.searcheverywhere.RecentFilesSEContributor.lambda$fetchWeightedElements$4(RecentFilesSEContributor.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.ide.actions.searcheverywhere.RecentFilesSEContributor.fetchWeightedElements(RecentFilesSEContributor.java:73)
	at com.intellij.ide.actions.searcheverywhere.PSIPresentationBgRendererWrapper.fetchWeightedElements(PSIPresentationBgRendererWrapper.java:58)
	at com.intellij.ide.actions.searcheverywhere.MixedResultsSearcher$ContributorSearchTask.run(MixedResultsSearcher.java:177)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:263)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by adietish** [comment]
@lstocchi, @jeffmaury:  I looked the error up, found several guys having this in their plugin.
Problem is that the editor tab title provider gets `project` and `file`.
I needed `editor` and thus made something like `FileEditorManager.getInstance(project).getEditors(file).toList()` . This needs to be execute in the UI thread and then causes the error in the issue.
To fix it i removed my need for the editor.

**Comment by adietish** [comment]
@lstocchi apparently can't replicate this on Linux. So maybe it's a MacOS only issue?
There are no reports in telemetry since this is an error that happens in platform when the platform calls my plugin.
