### ISSUE TITLE
Plugin stuck when facing resourceexception

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-kubernetes#417]
When testing https://github.com/redhat-developer/intellij-kubernetes/pull/409 I faced this fatal error.
1) have a tekton condition resource
2) open it
3) fatal error and the plugin become unresponsive

```
com.redhat.devtools.intellij.kubernetes.model.ResourceException: Invalid kubernetes yaml/json
	at com.redhat.devtools.intellij.kubernetes.editor.EditorResourceFactory.create(EditorResourceFactory.kt:68)
	at com.redhat.devtools.intellij.kubernetes.editor.EditorResourceFactory.create(EditorResourceFactory.kt:45)
	at com.redhat.devtools.intellij.kubernetes.editor.EditorResourceFactory.create(EditorResourceFactory.kt:32)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$1.invoke(ResourceEditor.kt:58)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$1.invoke(ResourceEditor.kt:58)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$editorResource$1.invoke(ResourceEditor.kt:125)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$editorResource$1.invoke(ResourceEditor.kt:124)
	at com.redhat.devtools.intellij.kubernetes.model.util.ResettableLazyProperty.get(ResettableLazyProperty.kt:30)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditorFactory.getExisting(ResourceEditorFactory.kt:106)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditorFactory.getFile(ResourceEditorFactory.kt:92)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditorFactory.access$getFile(ResourceEditorFactory.kt:33)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditorFactory$openEditor$1.invoke(ResourceEditorFactory.kt:79)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditorFactory$openEditor$1.invoke(ResourceEditorFactory.kt:78)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditorFactory.runAsync$lambda-2(ResourceEditorFactory.kt:158)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassCastException: class io.fabric8.kubernetes.api.model.Condition cannot be cast to class io.fabric8.kubernetes.api.model.HasMetadata (io.fabric8.kubernetes.api.model.Condition and io.fabric8.kubernetes.api.model.HasMetadata are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @2a986b12)
	at com.redhat.devtools.intellij.kubernetes.editor.EditorResourceFactory.create(EditorResourceFactory.kt:60)
	... 23 more

```

tekton resource 

```
apiVersion: "tekton.dev/v1alpha1"
kind: "Condition"
metadata:
  name: "file-exists"
  namespace: "default"
spec:
  check:
    image: "alpine"
    name: ""
    resources: {}
    script: "test -f $(resources.workspace.path)/$(params.path)"
  params:
  - name: "path"
    type: "string"
  resources:
  - name: "workspace"
    type: "git"

```

**Comment by adietish** [comment]
@lstocchi odd, I cannot reproduce this. Using your resource works just fine for me:
![grafik](https://user-images.githubusercontent.com/25126/173883925-7e7186f8-2eae-4cd2-bc46-34e5762ed071.png)
Any idea?

**Comment by lstocchi** [comment]
I'm not able to replicate it anymore with the main branch. Maybe my env was dirty :man_shrugging: Closing it.
