### ISSUE TITLE
"fatal IDE Error" (WebSocketHandshakeException) when trying to open a terminal to a container that is NOT running

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#502]
depends on #214 

**Steps:**
1. ASSERT: have a pod with a stopped coninter:
`alpine-container` terminates as soon as the bash script finished executing:
```
apiVersion: v1
kind: Pod
metadata:
  name: multi-pod2
spec:
  restartPolicy: Never
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
    - name: alpine-container
      image: alpine
      volumeMounts:
        - name: shared-data
          mountPath: /pod-data
      command: ["/bin/sh"]
      args: ["-c", "echo Hello, World!!! > /pod-data/index.html"]
```
2. EXEC: in resource tree: select Workloads > Pods >`multi-pod2` and pick "Open Terminal" in the context menu
3. ASSERT: terminal to the container `nginx-container` is openened.
4. EXEC: click on `alpine-container` in the list of containers

**Result:**
Fatal IDE error shows up, the details of it you'll get the following:
```
Exec Failure

io.fabric8.kubernetes.client.http.WebSocketHandshakeException
	at io.fabric8.kubernetes.client.okhttp.OkHttpWebSocketImpl$BuilderImpl$1.onFailure(OkHttpWebSocketImpl.java:66)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.lang.Throwable: waiting here
		at io.fabric8.kubernetes.client.utils.Utils.waitUntilReady(Utils.java:169)
		at io.fabric8.kubernetes.client.utils.Utils.waitUntilReadyOrFail(Utils.java:180)
		at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.exec(PodOperationsImpl.java:332)
		at io.fabric8.kubernetes.client.dsl.internal.core.v1.PodOperationsImpl.exec(PodOperationsImpl.java:85)
		at com.redhat.devtools.intellij.kubernetes.model.resource.ExecWatcher.watch(ExecWatcher.kt:38)
		at com.redhat.devtools.intellij.kubernetes.model.resource.NamespacedResourceOperator.watchExec(NamespacedResourceOperator.kt:109)
		at com.redhat.devtools.intellij.kubernetes.model.resource.kubernetes.NamespacedPodsOperator.watchExec(NamespacedPodsOperator.kt:42)
		at com.redhat.devtools.intellij.kubernetes.model.resource.kubernetes.NamespacedPodsOperator.watchExec(NamespacedPodsOperator.kt:26)
		at com.redhat.devtools.intellij.kubernetes.model.context.ActiveContext.watchExec(ActiveContext.kt:350)
		at com.redhat.devtools.intellij.kubernetes.model.ResourceModel.watchExec(ResourceModel.kt:215)
		at com.redhat.devtools.intellij.kubernetes.console.TerminalTab.createExecWatch(TerminalTab.kt:69)
		at com.redhat.devtools.intellij.kubernetes.console.TerminalTab.startWatch(TerminalTab.kt:35)
		at com.redhat.devtools.intellij.kubernetes.console.TerminalTab.startWatch(TerminalTab.kt:27)
		at com.redhat.devtools.intellij.kubernetes.console.ConsoleTab$ConsolesPanel$create$$inlined$runAsync$1.run(promise.kt:402)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
		at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
		at java.base/java.security.AccessController.doPrivileged(Native Method)
		at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
		... 1 more
Caused by: java.net.ProtocolException: Expected HTTP 101 response but was '500 Internal Server Error'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196)
	... 5 more
```

**Comment by adietish** [comment]
This is caused by logging to error in the client library: https://github.com/fabric8io/kubernetes-client/blob/v5.12.2/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/dsl/internal/ExecWebSocketListener.java#L215
```
LOGGER.error("Exec Failure", t);
```

**Comment by adietish** [comment]
> Other issue that I found is that when this exception is raised, there is no way to open terminal when the container is really started.

Thanks for reporting this. I'll file this to it's own issue. #214 is already a huge change and this issue here is focused on the sole problem of error logging within the kubernetes-client to bubble up to the platform.

**Comment by adietish** [comment]
A possible solution is to register a subclass of `ITNReporter` that is able to filter errors:
plugin.xml:
``` 
        <errorHandler implementation="com.redhat.devtools.intellij.kubernetes.Fabric8FilteringErrorReporter" />
```
```
class Fabric8FilteringErrorReporter: ITNReporter() {

    override fun showErrorInRelease(event: IdeaLoggingEvent): Boolean {
        return false
    }
}
```
The problem though is that plugins which use `ITNReporter` are rejected. A subclass may pass though.

**Comment by adietish** [comment]
Another possibility is to use the latest kubernetes-client (v6.x) which does not log an error any more if you register a listener:
```java
        if (listener != null) {
          ExecListener.Response execResponse = null;
          if (response != null) {
            execResponse = new SimpleResponse(response);
          }
          listener.onFailure(t, execResponse);
        } else {
          LOGGER.error("Exec Failure", t);
        }
```
I'd register a listener in `ExecWatcher`:
```kotlin
        val op = (operation as? Containerable<String, ContainerResource<*, *, *, *, *, *, *, *, *, *>>?)
            ?.inContainer(containerId)
            ?.redirectingInput()
            ?.redirectingOutput()
            ?.redirectingError()
            ?.withTTY()
            ?.usingListener(null) as? Execable<String, ExecWatch>
            ?: return null

        return op.exec("sh")
```
