### ISSUE TITLE
java.lang.ClassCastException: Error cannot be cast to Different 

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-kubernetes#619]
I dont know how to reproduce this so far, but I faced this when editing a multi-resource document, pushing it repeatedly to the Red Hat Developer Sandbox.
To detect it I added a ClassCastException breakpoint that was invoked at `PushNotification#show`.

```java
java.lang.ClassCastException: class com.redhat.devtools.intellij.kubernetes.editor.Error cannot be cast to class com.redhat.devtools.intellij.kubernetes.editor.Different (com.redhat.devtools.intellij.kubernetes.editor.Error and com.redhat.devtools.intellij.kubernetes.editor.Different are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @2b343b60)
	at com.redhat.devtools.intellij.kubernetes.editor.notification.PushNotification.show(PushNotification.kt:40)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$showPushNotification$1.invoke(ResourceEditor.kt:194)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor$showPushNotification$1.invoke(ResourceEditor.kt:191)
	at com.redhat.devtools.intellij.kubernetes.editor.ResourceEditor.runInUI$lambda$4(ResourceEditor.kt:457)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by adietish** [comment]
#624 fixed this issue. Closing.
