### ISSUE TITLE
got 'Migrate com.redhat.devtools.intellij.kubernetes.KubernetesPluginInitializer to ProjectActivity' message running from dev env in 2023.3 

### ISSUE THREAD

**Issue by sbouchet** [redhat-developer/intellij-kubernetes#706]
IDEA 2023.3.2, running grdale runIde task, got the below error each time: 

```
2024-01-11 11:40:56,742 [  10770]   WARN - #c.i.i.s.i.StartupManagerImpl - Migrate com.redhat.devtools.intellij.kubernetes.KubernetesPluginInitializer to ProjectActivity [Plugin: com.redhat.devtools.intellij.kubernetes]
com.intellij.diagnostic.PluginException: Migrate com.redhat.devtools.intellij.kubernetes.KubernetesPluginInitializer to ProjectActivity [Plugin: com.redhat.devtools.intellij.kubernetes]
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:277)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:69)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invokeSuspend(StartupManagerImpl.kt:192)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3$2.invoke(StartupManagerImpl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$3.invokeSuspend(StartupManagerImpl.kt:191)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by adietish** [comment]
`ProjectActivity` was introduced in `IC-2022.3` or `IC-2023.1`. We will be able to migrate once we bump the minimum supported version to these versions (we are currently on `IC-2022.1`).

![image](https://github.com/redhat-developer/intellij-kubernetes/assets/25126/7d359f42-fa3d-4d18-966b-666db2746c8a)

**Comment by adietish** [comment]
We're currently requiring IC-2023.1, we're still not meeting the min requirement of IC-2023.2. 
We could bump this though as it's 1.5y old. There's no need though, there's no breaking when using `PluginInitializer`, it's only strongly warning.
